config:
    use_colors: True
default:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: "{{ env_var('USERNAME') }}"
      pass: "{{ env_var('PASSWORD') }}"
      dbname: dvd_rental
      schema: dev
    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: "{{ env_var('USERNAME') }}"
      pass: "{{ env_var('PASSWORD') }}"
      dbname: dvd_rental
      schema: analytics
